# This secret is referenced in bootstrap/bootstrap-resources/templates/cluster-issuer.yaml
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: lets-encrypt-do-dns
data:
  # Add your DigitalOcean API key
  access-token: <insert your encoded api key>